# -*- coding: utf-8 -*-
"""Process Mining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKk_nwzUWIcIx3DqqmiT2vE1wpRtXUQr
"""

!pip install pm4py

!pip install matplotlib

import pm4py
import pandas as pd
from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.visualization.petri_net import visualizer as pn_visualizer

# Import the log
log = xes_importer.apply('/content/drive/MyDrive/dataset/BPI Challenge 2017.xes')

# Verify
print(f"Successfully loaded {len(log)} traces.")

log

# Convert the event log to a pandas DataFrame
df_view = pm4py.convert_to_dataframe(log)

# Display the first 20 rows of the event log
df_view.head(20)

# Get the variants from the log
from pm4py.algo.filtering.log.variants import variants_filter
variants = variants_filter.get_variants(log)

# Count and sort the variants by frequency
from collections import Counter
variants_count = Counter()
for v in variants:
    variants_count[v] += len(variants[v])

# Display the top most frequent variants (the "Class Log" variants)
top_variants = sorted(variants_count.items(), key=lambda x: x[1], reverse=True)[:50]

for i, (variant, count) in enumerate(top_variants):
    print(f"Variant {i+1} (Occurrences: {count}):")
    print(f" Sequence: {variant}\n")

import pm4py
from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.visualization.petri_net import visualizer as pn_visualizer

# Discover the Petri net from the log
net, initial_marking, final_marking = pm4py.discover_petri_net_inductive(log)

# visualization
gviz = pn_visualizer.apply(net, initial_marking, final_marking)

# Display the image
pn_visualizer.view(gviz)

# Save the image
pn_visualizer.save(gviz, "classical_petri_net.png")

# discover_dfg returns (dfg, start_activities, end_activities)
dfg, start_activities, end_activities = pm4py.discover_dfg(log)

# Visualize
from pm4py.visualization.dfg import visualizer as dfg_visualizer
gviz = dfg_visualizer.apply(dfg, log=log, variant=dfg_visualizer.Variants.FREQUENCY, parameters={dfg_visualizer.Variants.FREQUENCY.value.Parameters.START_ACTIVITIES: start_activities, dfg_visualizer.Variants.FREQUENCY.value.Parameters.END_ACTIVITIES: end_activities})
dfg_visualizer.view(gviz)

import pm4py
from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.visualization.petri_net import visualizer as pn_visualizer

# Since the specific clustering module was not found, we will use variant-based filtering
# to group the most frequent process patterns as clusters.
from pm4py.algo.filtering.log.variants import variants_filter

# Get variants
variants = variants_filter.get_variants(log)
# Sort variants by frequency
ordered_variants = sorted(variants.items(), key=lambda x: len(x[1]), reverse=True)

# We will treat the top 10 most frequent variants as our 'clusters'
no_clusters = 10

for i in range(no_clusters):
    variant_tuple, cluster_traces = ordered_variants[i]
    # Convert the list of traces back to a Log object
    cluster_log = pm4py.objects.log.obj.EventLog(cluster_traces)

    print(f"--- Visualizing Cluster {i+1} (Variant Frequency: {len(cluster_log)} traces) ---")

    # Discover a Petri net for this specific variant cluster
    net, im, fm = pm4py.discover_petri_net_inductive(cluster_log)

    # Show the model
    gviz = pn_visualizer.apply(net, im, fm)
    pn_visualizer.view(gviz)

    # Save the model
    pn_visualizer.save(gviz, f"cluster_{i+1}_model.png")