# -*- coding: utf-8 -*-
"""Classical model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14H3yeacG8tsxcf2fsLXdbAuO_Rrx8Otn
"""

!pip install pm4py

import pm4py
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Import Log"""

from google.colab import drive
drive.mount('/content/drive')

log = pm4py.read_xes('/content/drive/MyDrive/dataset/BPI Challenge 2017.xes')

# Verify
print(f"Successfully loaded {len(log)} traces.")

"""# Filter Log A"""

log_a_filtered = pm4py.filter_event_attribute_values(
    log,
    "concept:name",
    ["A_Pending", "A_Cancelled", "A_Denied"],
    level="event",
    retain=True
)

# Filter traces to only those ending in the desired outcome activities
admitted_end_activities = ["A_Pending", "A_Cancelled", "A_Denied"]
log_a = pm4py.filter_end_activities(
    log_A_filtered,
    admitted_end_activities
)

print(f"Filtered log contains {len(log_A)} traces.")

"""# Filter Log A and O"""

log_ao = log[log['concept:name'].str.startswith(('A_', 'O_'))].copy()

# Verify
remaining_activities = log_ao['concept:name'].unique()
print(f"Remaining activities: {remaining_activities}")
print(f"Number of events after filtering W_: {len(log_ao)}")

"""# Distribution of End Activities

Distribution of end activities for event log
"""

end_activities = pm4py.get_end_activities(log)
end_activities

end_activities_a = pm4py.get_end_activities(log_a)
end_activities_a

end_activities_ao = pm4py.get_end_activities(log_ao)
end_activities_ao

"""#### Visualisation Distribution"""

activities = list(end_activities.keys())
counts = [end_activities[activity] for activity in activities]

bars = plt.bar(activities, counts, color='skyblue')

plt.xlabel('End Events')
plt.ylabel('Count')
plt.title('Distribution by End Event')
plt.xticks(rotation=45)
plt.tight_layout()

for i, count in enumerate(counts):
    plt.text(i, count, str(count), ha='center', va='bottom')

plt.show()

activities = list(end_activities_a.keys())
counts = [end_activities_a[activity] for activity in activities]

bars = plt.bar(activities, counts, color='red')

plt.xlabel('End Events')
plt.ylabel('Count')
plt.title('Distribution of Traces by End Event')
plt.xticks(rotation=45)
plt.tight_layout()

# Add values on the bars
for i, count in enumerate(counts):
    plt.text(i, count, str(count), ha='center', va='bottom')

plt.show()

activities = list(end_activities_ao.keys())
counts = [end_activities_ao[activity] for activity in activities]

bars = plt.bar(activities, counts, color='green')

plt.xlabel('End Events')
plt.ylabel('Count')
plt.title('Distribution of Traces by End Event')
plt.xticks(rotation=45)
plt.tight_layout()

# Add values on the bars
for i, count in enumerate(counts):
    plt.text(i, count, str(count), ha='center', va='bottom')

plt.show()

"""#### Visualisation Successful and Unsuccessful Distribution

categorized as either successful or unsuccessful applications (A_Pending) is successful, whereas (A_Denied) and (A_Cancelled) is unsuccessful.
"""

successful_counts = [end_activities_a.get('A_Pending', 0)]
unsuccessful_counts = [count for activity, count in end_activities_a.items() if activity != 'A_Pending']

fig, ax = plt.subplots(figsize=(10, 6))



ax.bar('Successful Applications', successful_counts, color='limegreen', label='Successful Applications')
ax.bar('Unsuccessful Applications', sum(unsuccessful_counts), color='navy', label='Unsuccessful Applications')

for bar, count in zip(ax.patches, [successful_counts[0], sum(unsuccessful_counts)]):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2, height, count, ha='center', va='bottom')

ax.set_xlabel('Application Outcome')
ax.set_ylabel('Count')
ax.set_title('Distribution of Traces by Application Outcome')
ax.legend()

plt.show()

"""# analyzing the flow"""

pm4py.get_start_activities(log_ao)

len(pm4py.get_variants_as_tuples(log_ao))

"""Transform the log into a dataframe"""

df = pm4py.convert_to_dataframe(log_ao)
df.head(5)

"""# Process Model Visualization

#### Visualisation DFG

##### Full Log A_, O_, W_
"""

dfg, start_activities, end_activities_ao = pm4py.discover_dfg(log)
pm4py.view_dfg(dfg, start_activities, end_activities)

"""##### Filtered Log A_ and O"""

dfg, start_activities, end_activities_ao = pm4py.discover_dfg(log_ao)
pm4py.view_dfg(dfg, start_activities, end_activities_ao)

"""#### Alpha miner - net (petri net)

##### Full log
"""

net, initial_marking, final_marking = pm4py.discover_petri_net_alpha(log)
pm4py.view_petri_net(net)

"""##### Filtered log A_, and O_"""

net, initial_marking, final_marking = pm4py.discover_petri_net_alpha(log_ao)
pm4py.view_petri_net(net)

"""#### Inductive miner

##### Filtered Log A_, and O_
"""

net, initial_marking, final_marking = pm4py.discover_petri_net_inductive(log_ao)
tree = pm4py.discover_process_tree_inductive(log_ao)
pm4py.view_process_tree(tree)

"""##### Full Log"""

net, initial_marking, final_marking = pm4py.discover_petri_net_inductive(log)
tree = pm4py.discover_process_tree_inductive(log)
pm4py.view_process_tree(tree)

"""#### Heuristic miner

##### filtered log A_ and O_
"""

heu_net = pm4py.discover_heuristics_net(log_ao, dependency_threshold=0.90)
pm4py.view_heuristics_net(heu_net)

"""##### Full log"""

heu_net = pm4py.discover_heuristics_net(log, dependency_threshold=0.90)
pm4py.view_heuristics_net(heu_net)