# -*- coding: utf-8 -*-
"""Object Centric workground.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpTHFm_vc8Un2hIFmFHd0J39ci81u6ty
"""

!pip install pm4py

import pm4py
from pm4py.algo.discovery.ocel.ocpn import algorithm as ocpn_discovery
from pm4py.visualization.ocel.ocpn import visualizer as ocpn_visualizer

from pm4py.objects.log.importer.xes import importer as xes_importer

# Load log
log = xes_importer.apply('/content/drive/MyDrive/dataset/BPI Challenge 2017.xes')

# Convert to OCEL
ocel = pm4py.convert_log_to_ocel(log, activity_column='concept:name',
                                 timestamp_column='time:timestamp',
                                 object_types=['case:concept:name'])

log

ocel = pm4py.convert_log_to_ocel(
    log,
    activity_column='concept:name',
    timestamp_column='time:timestamp',
    object_types=['case:concept:name', 'case:OfferID', 'case:EventID']
)

# nets for A, O, and W
ocpn = ocpn_discovery.apply(ocel, parameters={
    "noise_threshold": 0.1
})

gviz = ocpn_visualizer.apply(ocpn)
ocpn_visualizer.view(gviz)

gviz = ocpn_visualizer.apply(ocpn)

# Display
ocpn_visualizer.view(gviz)

# Save
ocpn_visualizer.save(gviz, "OCPN_BPI2017_Model.png")