# -*- coding: utf-8 -*-
"""Process Mining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKk_nwzUWIcIx3DqqmiT2vE1wpRtXUQr
"""

!pip install pm4py

!pip install matplotlib

import pm4py
import pandas as pd
from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.visualization.petri_net import visualizer as pn_visualizer

# Import the log
log = xes_importer.apply('/content/drive/MyDrive/dataset/BPI Challenge 2017.xes')

# Verify
print(f"Successfully loaded {len(log)} traces.")

log

# Convert the event log to a pandas DataFrame
df_view = pm4py.convert_to_dataframe(log)

# Display the first 20 rows of the event log
df_view.head(50)

from pm4py.algo.filtering.log.variants import variants_filter
variants = variants_filter.get_variants(log)

# Count and sort the variants by frequency
from collections import Counter
variants_count = Counter()
for v in variants:
    variants_count[v] += len(variants[v])

# Display
group_variants = sorted(variants_count.items(), key=lambda x: x[1], reverse=True)[:100]

for i, (variant, count) in enumerate(group_variants):
    print(f"Variant {i+1} (Occurrences: {count}):")
    print(f" Sequence: {variant}\n")

from pm4py.visualization.petri_net import visualizer as pn_visualizer
import random

# 1. Get the top 3 variants
variants = pm4py.get_variants(log)
sorted_variants = sorted(variants.items(), key=lambda x: len(x[1]), reverse=True)

for i in range(1, 4):
    variant_tuple, traces = sorted_variants[i-1]
    variant_log = pm4py.objects.log.obj.EventLog(traces)

    print(f"--- Inductive Miner: Variant {i} (Count: {len(variant_log)}) ---")

    # Petri net
    net, im, fm = pm4py.discover_petri_net_inductive(variant_log)

    for arc in net.arcs:
        color = "#%06x" % random.randint(0, 0xFFFFFF)
        arc.properties["color"] = color
        arc.properties["penwidth"] = "1.5"

    # Visualize and Save
    gviz = pn_visualizer.apply(net, im, fm)
    pn_visualizer.view(gviz)
    pn_visualizer.save(gviz, f'inductive_variant_{i}_colored.png')

import pm4py
from pm4py.visualization.dfg import visualizer as dfg_visualizer

#  DFG
dfg, start_activities, end_activities = pm4py.discover_dfg(log)

# counts all activities are present
activities_count = pm4py.get_event_attribute_values(log, "concept:name")

# Visualize
gviz = dfg_visualizer.apply(dfg,
                            log=log,
                            variant=dfg_visualizer.Variants.FREQUENCY,
                            parameters={
                                "start_activities": start_activities,
                                "end_activities": end_activities,
                                "max_no_edges": 0
                            })

dfg_visualizer.view(gviz)
dfg_visualizer.save(gviz, "clustered_activities_only.png")



from pm4py.visualization.dfg import visualizer as dfg_visualizer

# DFG
dfg_perf, start_act, end_act = pm4py.discover_performance_dfg(log)

# DFG
gviz_perf = dfg_visualizer.apply(dfg_perf,
                                  log=log,
                                  variant=dfg_visualizer.Variants.PERFORMANCE,
                                  parameters={dfg_visualizer.Variants.PERFORMANCE.value.Parameters.AGGREGATION_MEASURE: 'mean'})

dfg_visualizer.view(gviz_perf)

# Save visualization
dfg_visualizer.save(gviz_perf, "performance_dfg.png")

import pm4py
from pm4py.visualization.dfg import visualizer as dfg_visualizer

# filter for the top 3 variants

filtered_log_top_3 = pm4py.filter_variants_top_k(log, k=3)

print(f"Analyzing performance for {len(filtered_log_top_3)} traces (Top 3 variants).")

#  DFG
dfg_perf_top3, start_act_top3, end_act_top3 = pm4py.discover_performance_dfg(filtered_log_top_3)

# Visualize
gviz_perf_top3 = dfg_visualizer.apply(dfg_perf_top3,
                                       log=filtered_log_top_3,
                                       variant=dfg_visualizer.Variants.PERFORMANCE,
                                       parameters={dfg_visualizer.Variants.PERFORMANCE.value.Parameters.AGGREGATION_MEASURE: 'mean'})

dfg_visualizer.view(gviz_perf_top3)
dfg_visualizer.save(gviz_perf_top3, "top_3_variants_performance.png")

from pm4py.algo.filtering.log.variants import variants_filter
from collections import Counter

# Get variants
variants = variants_filter.get_variants(log)

# Count and sort by frequency
variants_count = Counter({v: len(traces) for v, traces in variants.items()})
top_3_variants = variants_count.most_common(3)

print(f"--- Top 3 Process Variants ---\n")
for i, (variant, count) in enumerate(top_3_variants):
    print(f"Variant {i+1} (Occurrences: {count}):")
    print(f"Sequence: {variant}\n")

import pm4py
from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.visualization.petri_net import visualizer as pn_visualizer

# Petri net from the log
net, initial_marking, final_marking = pm4py.discover_petri_net_inductive(log)

# visualization
gviz = pn_visualizer.apply(net, initial_marking, final_marking)

# Display the image
pn_visualizer.view(gviz)

# Save the image
pn_visualizer.save(gviz, "classical_petri_net.png")

# discover_dfg returns (dfg, start_activities, end_activities)
dfg, start_activities, end_activities = pm4py.discover_dfg(log)

# Visualize
from pm4py.visualization.dfg import visualizer as dfg_visualizer
gviz = dfg_visualizer.apply(dfg, log=log, variant=dfg_visualizer.Variants.FREQUENCY, parameters={dfg_visualizer.Variants.FREQUENCY.value.Parameters.START_ACTIVITIES: start_activities, dfg_visualizer.Variants.FREQUENCY.value.Parameters.END_ACTIVITIES: end_activities})
dfg_visualizer.view(gviz)

from pm4py.algo.discovery.inductive import algorithm as inductive_miner
from pm4py.visualization.petri_net import visualizer as pn_visualizer
from pm4py.algo.filtering.log.variants import variants_filter

# Get variants
variants = variants_filter.get_variants(log)
# Sort variants by frequency
ordered_variants = sorted(variants.items(), key=lambda x: len(x[1]), reverse=True)

# frequent variants
no_clusters = 10

for i in range(no_clusters):
    variant_tuple, cluster_traces = ordered_variants[i]

    cluster_log = pm4py.objects.log.obj.EventLog(cluster_traces)

    print(f"--- Visualizing Cluster {i+1} (Variant Frequency: {len(cluster_log)} traces) ---")

    # Petri net
    net, im, fm = pm4py.discover_petri_net_inductive(cluster_log)

    # Show the model
    gviz = pn_visualizer.apply(net, im, fm)
    pn_visualizer.view(gviz)

    # Save the model
    pn_visualizer.save(gviz, f"cluster_{i+1}_model.png")

from pm4py.visualization.petri_net import visualizer as pn_visualizer

# Petri net Inductive Miner
net, initial_marking, final_marking = pm4py.discover_petri_net_inductive(log)

# Petri net
# The format can be specified in the parameters if needed for saving
gviz = pn_visualizer.apply(net, initial_marking, final_marking)

# View the model
pn_visualizer.view(gviz)

# Save the model
pn_visualizer.save(gviz, "inductive_miner_classical_model.png")

# Filter the log
filtered_log = pm4py.filter_variants_top_k(log, k=50)

print(f"Original log: {len(log)} traces")
print(f"Filtered log (top 50 variants): {len(filtered_log)} traces")

# Discover Petri net discovery
net, im, fm = pm4py.discover_petri_net_inductive(filtered_log)

# Visualize and save
gviz = pn_visualizer.apply(net, im, fm)
pn_visualizer.view(gviz)
pn_visualizer.save(gviz, "classical_baseline.png")